export const GET_ALL_RECIPES_STARTED = 'GET_RECIPES_STARTED'
export const GET_ALL_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS'
export const GET_ALL_RECIPES_FAILURE = 'GET_RECIPES_FAILURE'

export const GET_ONE_RECIPE_STARTED = 'GET_ONE_RECIPE_STARTED'
export const GET_ONE_RECIPE_SUCCESS = 'GET_ONE_RECIPE_SUCCESS'
export const GET_ONE_RECIPE_FAILURE = 'GET_ONE_RECIPE_FAILURE'

export const SAVE_RECIPE_SUCCESS = 'SAVE_RECIPE_SUCCESS'
export const SAVE_RECIPE_FAILURE = 'SAVE_RECIPE_FAILURE'

export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS'
export const UPDATE_RECIPE_FAILURE = 'UPDATE_RECIPE_FAILURE'

export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS'
export const DELETE_RECIPE_FAILURE = 'DELETE_RECIPE_FAILURE'